ARG NODE_VERSION=16
ARG CLIENT_PORT=3000

FROM node as builder

RUN apt update && apt install -y nodejs && apt install -y npm

WORKDIR /app

COPY ./packages/client/package.json .
COPY ./packages/client/ .

RUN npm install
RUN npm run build

FROM nginx:alpine
WORKDIR /app

COPY --from=builder /app/dist/ /app/
COPY --from=builder /app/nginx.conf /etc/nginx/nginx.conf

EXPOSE $CLIENT_PORT
CMD [ "nginx", "-g", "daemon off;" ]
