name: Push To Yandex Cloud CR


on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpr86nohje7jd3nt11h
          CR_REPOSITORY: game.practicum.yandex.ru
          IMAGE_TAG: ${{ github.sha }}
          CLIENT_PORT: 3000
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
          SERVER_NAME: wordrunners-bumble-20.ya-praktikum.tech
          SERVER_PORT: 5000
          CLIENT_IMAGE: cr.yandex/crpr86nohje7jd3nt11h/traffic-racer/practicum-client:${{ github.sha }}
          SERVER_IMAGE: cr.yandex/crpr86nohje7jd3nt11h/traffic-racer/practicum-server:${{ github.sha }}
        run: |
          docker compose build
          docker tag practicum-client:latest ${{env.CLIENT_IMAGE}}
          docker push ${{env.CLIENT_IMAGE}}
          docker tag practicum-server:latest ${{env.SERVER_IMAGE}}
          docker push  ${{env.SERVER_IMAGE}}
